UmidadeRelativa:
    d_threshold: 12
    z_threshold: 3
    margins: 3

PressaoAtmosferica:
    d_threshold: 50
    z_threshold: 7
    margins: 10
    min_value: 905
    max_value: 950

TemperaturaDoAr:
    d_threshold: 6
    z_threshold: 4
    margins: 2
    min_value: 5
    max_value: 45

TemperaturaInterna:
    d_threshold: 6
    z_threshold: 4
    margins: 3

PontoDeOrvalho:
    d_threshold: 3.5
    z_threshold: 4
    margins: 5

SensacaoTermica:
    d_threshold: 4
    z_threshold: 10
    margins: 3

RadiacaoSolar:
    d_threshold: 850
    z_threshold: 50
    margins: 5
    nz_threshold: 3
    min_value: 0

DirecaoDoVento:
    z_threshold: 3
    margins: 3
    min_value: 0
    max_value: 360

VelocidadeDoVento:
    d_threshold: 8
    z_threshold: 5
    margins: 3

Precipitacao:
    d_threshold: 30
    z_threshold: 1440
    nz_threshold: 8
    margins: 1
    min_value: 0
