## --------------
## Possible keys
##
## interpolation
##   max_interpolation_size: int
##
## regression
##   max_region_size: int
##   lookbackSize: int
##   extra_features: list of strings (features)
##   interpolate_kwargs: dict - pd.interpolate kwargs -
##                              cannot include `limit` already defined by max_region_size
## idw: bool
## fill_ow: bool
## ---------------

UmidadeRelativa:
    idw: true
    fill_ow: true

TemperaturaDoAr:
    idw: true
    fill_ow: true

DirecaoDoVento:
    fill_ow: true

VelocidadeDoVento:
    idw: true
    fill_ow: true

Precipitacao:
    idw: true
    fill_ow: true

PressaoAtmosferica:
    idw: true
    interpolation:
        max_interpolation_size: 500

RadiacaoSolar:
    idw: true
    regression:
        max_region_size: 1000
        lookbackSize: 8
        extra_features: ['Hora', 'TemperaturaDoAr_0', 'Precipitacao_0', 'UmidadeRelativa_0']

PontoDeOrvalho:
    idw: true
    regression:
        max_region_size: 500
        lookbackSize: 6
        extra_features: ['Hora', 'TemperaturaDoAr_0', 'UmidadeRelativa_0']


## ========== Not Used ==========
# # TemperaturaInterna:
# #     interpolation:
# #         max_interpolation_size: 5
# #     regression:
# #         max_region_size: 100
# #         lookbackSize: 6
# #         extra_features: ['Hora']

# # SensacaoTermica:
# #     interpolation:
# #         max_interpolation_size: 5
# #     regression:
# #         max_region_size: 100
# #         lookbackSize: 6
# #         extra_features: ['Hora','Mes']
# #     idw: true
# #     fill_ow: true
